JEIEvents.hideItems(factory => {
    factory.hide('@allthemodium')
})
JEIEvents.addItems(factory => {

    factory.add('allthemodium:teleport_pad')
    factory.add('allthemodium:allthemodium_ingot')
    factory.add('allthemodium:allthemodium_ore')
    factory.add('allthemodium:vibranium_ingot')
    factory.add('allthemodium:other_vibranium_ore')
    factory.add('allthemodium:unobtainium_ingot')
    factory.add('allthemodium:unobtainium_ore')
    factory.add('allthemodium:raw_allthemodium')
    factory.add('allthemodium:raw_vibranium')
    factory.add('allthemodium:raw_unobtainium')
    factory.add('allthemodium:allthemodium_block')
    factory.add('allthemodium:vibranium_block')
    factory.add('allthemodium:unobtainium_block')

    factory.add('ironfurnaces:allthemodium_furnace')
    factory.add('ironfurnaces:upgrade_allthemodium')
    factory.add('ironfurnaces:upgrade_vibranium')
    factory.add('ironfurnaces:upgrade_unobtainium')
    factory.add('ironfurnaces:vibranium_furnace')
    factory.add('ironfurnaces:unobtainium_furnace')
})